/*
 * Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import type {
  GenericError,
  Node,
  NodeCallback,
} from '@ping-identity/rn-types';
import type { LoggerInstance, NativeLoggerHandle } from '@react-native-pingidentity/logger';
import type { SessionStorage } from '@react-native-pingidentity/storage';

/**
 * Node discriminator returned by the Journey bridge.
 */
export type JourneyNodeType =
  | 'ContinueNode'
  | 'ErrorNode'
  | 'FailureNode'
  | 'SuccessNode';

/**
 * Native callback payload surfaced to JavaScript.
 */
export type JourneyCallback = NodeCallback & {
  /** Native callback type (for example, `NameCallback`). */
  type: string;
  /** Optional user-facing prompt string emitted by native. */
  prompt?: string;
  /** Optional user-facing message emitted by native. */
  message?: string;
  /** Optional callback value emitted by native. */
  value?: unknown;
  /** Optional callback metadata emitted by native. */
  [key: string]: unknown;
};

/**
 * Journey node payload returned by native execution.
 */
export type JourneyNode = Node & {
  /**
   * Native node identifier generated by the bridge.
   *
   * @remarks
   * This is bridge-specific and currently separate from `authId`.
   */
  id?: string;
  /** Terminal/non-terminal node discriminator. */
  type?: JourneyNodeType;
  /** Optional node-level message from native/server. */
  message?: string;
  /** Optional failure cause message for `FailureNode`. */
  cause?: string;
  /** Optional session payload for `SuccessNode`. */
  session?: Record<string, unknown>;
  /** Callback collection when additional user input is required. */
  callbacks?: JourneyCallback[];
};

/**
 * Journey client base configuration.
 */
export type JourneyConfig = {
  /**
   * Base AM/Ping server URL.
   */
  serverUrl: string;
  /**
   * Optional Journey realm.
   */
  realm?: string;
  /**
   * Optional Journey cookie name override.
   */
  cookie?: string;
  /**
   * Optional OIDC client identifier for Journey+OIDC composition.
   */
  clientId?: string;
  /**
   * Optional OIDC discovery endpoint.
   */
  discoveryEndpoint?: string;
  /**
   * Optional OIDC redirect URI.
   */
  redirectUri?: string;
  /**
   * Optional OIDC scopes for post-auth token flows.
   */
  scopes?: string[];
  /**
   * Optional JavaScript logger instance.
   */
  logger?: LoggerInstance;
  /**
   * Optional native logger handle.
   */
  nativeLogger?: NativeLoggerHandle;
};

/**
 * Optional Journey module integrations.
 */
export type JourneyModules = {
  /**
   * Session module configuration.
   */
  session?: {
    /**
     * Session storage handle created by the storage module.
     */
    storage?: SessionStorage;
  };
};

/**
 * Optional flags when starting a Journey.
 */
export type JourneyStartOptions = {
  /**
   * Force authentication even if an SSO session exists.
   */
  forceAuth?: boolean;
  /**
   * Ignore existing session state and start a fresh flow.
   */
  noSession?: boolean;
};

/**
 * Callback input value submitted to `next()`.
 */
export type JourneyCallbackInputValue =
  | string
  | number
  | boolean
  | null
  | Record<string, unknown>
  | Array<unknown>;

/**
 * Callback mutation entry submitted to `next()`.
 */
export type JourneyCallbackInput = {
  /** Callback type to mutate. */
  type: string;
  /** Callback value to apply. */
  value?: JourneyCallbackInputValue;
  /**
   * Optional zero-based index when multiple callbacks share the same `type`.
   */
  index?: number;
};

/**
 * Payload for advancing a Journey node.
 */
export type JourneyNextInput = {
  /**
   * Callback mutations to apply before calling native `next()`.
   */
  callbacks?: JourneyCallbackInput[];
};

/**
 * User profile claims resolved from OIDC userinfo.
 */
export type JourneyUserInfo = Record<string, unknown>;

/**
 * Session payload exposed by `user()`.
 */
export type JourneyUserSession = {
  /**
   * Access token string.
   */
  accessToken: string;
  /**
   * Optional refresh token string.
   */
  refreshToken?: string;
  /**
   * Optional token expiry in seconds.
   */
  expiresIn?: number;
  /**
   * Optional user profile claims.
   */
  userInfo?: JourneyUserInfo;
};

/**
 * Journey error payload contract.
 */
export type JourneyError = GenericError;

/**
 * Stable Journey error codes surfaced by native and JS guardrails.
 */
export type JourneyErrorCode =
  | 'JOURNEY_CONFIG_ERROR'
  | 'JOURNEY_INIT_ERROR'
  | 'JOURNEY_START_ERROR'
  | 'JOURNEY_NEXT_ERROR'
  | 'JOURNEY_RESUME_ERROR'
  | 'JOURNEY_USER_ERROR'
  | 'JOURNEY_LOGOUT_ERROR'
  | 'JOURNEY_DISPOSE_ERROR'
  | 'JOURNEY_STATE_ERROR'
  | 'JOURNEY_CALLBACK_APPLY_ERROR'
  | 'JOURNEY_UNSUPPORTED_CALLBACK_ERROR'
  | 'JOURNEY_MISSING_INTEGRATION_ERROR';

/**
 * Native-backed Journey client contract.
 */
export type JourneyClient = {
  /**
   * Explicitly initialize the native Journey instance.
   *
   * @returns Native Journey instance identifier.
   * @throws {JourneyError} When the Journey cannot be configured.
   */
  init: () => Promise<string>;

  /**
   * Returns the native Journey instance identifier.
   *
   * @returns Native Journey instance identifier.
   * @throws {JourneyError} When the Journey is not configured.
   */
  getId: () => Promise<string>;

  /**
   * Start a Journey by name.
   *
   * @param journeyName - Journey/tree name configured on the server.
   * @param options - Optional start flags.
   * @returns The first Journey node.
   * @throws {JourneyError} When start fails.
   */
  start: (
    journeyName: string,
    options?: JourneyStartOptions
  ) => Promise<JourneyNode>;

  /**
   * Advance an active Journey by applying callback input.
   *
   * @param input - Callback value payload for the active node.
   * @returns Next Journey node.
   * @throws {JourneyError} When callback application or progression fails.
   */
  next: (input?: JourneyNextInput) => Promise<JourneyNode>;

  /**
   * Resume a suspended Journey flow from a deep link URL.
   *
   * @param uri - Resume URI provided by native/server.
   * @returns Resumed Journey node.
   * @throws {JourneyError} When resume fails.
   */
  resume: (uri: string) => Promise<JourneyNode>;

  /**
   * Resolve active user session details.
   *
   * @returns Session payload, or `null` when no active session exists.
   * @throws {JourneyError} When session retrieval fails.
   */
  user: () => Promise<JourneyUserSession | null>;

  /**
   * Logout active Journey user/session.
   *
   * @returns `true` when logout succeeds.
   * @throws {JourneyError} When logout fails.
   */
  logoutUser: () => Promise<boolean>;

  /**
   * Dispose the native Journey instance and release runtime state.
   *
   * @returns Promise resolved when disposal completes.
   * @throws {JourneyError} When disposal fails.
   */
  dispose: () => Promise<void>;
};
