ENV['RCT_NEW_ARCH_ENABLED'] = "1"   # New arch flag in client app
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PingSampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  pod 'PingJourney',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4325-Journey-POC-RN/PingJourney.podspec'
  pod 'PingStorage',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/1.3.0-beta2/PingStorage.podspec'
  pod 'PingOrchestrate',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/1.3.0-beta2/PingOrchestrate.podspec'
  pod 'PingLogger',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/1.3.0-beta2/PingLogger.podspec'
  pod 'PingOidc',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/1.3.0-beta2/PingOidc.podspec'
  pod 'RNPingCore', :path => '../../packages/core'
  
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
