# Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.

ENV['RCT_NEW_ARCH_ENABLED'] = "1"   # New arch flag in client app
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PingSampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  pod 'PingBrowser',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingBrowser.podspec'
  pod 'PingJourney',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingJourney.podspec'
  pod 'PingStorage',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingStorage.podspec'
  pod 'PingOrchestrate',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingOrchestrate.podspec'
  pod 'PingLogger',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingLogger.podspec'
  pod 'PingDeviceId',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingDeviceId.podspec'
  pod 'PingDeviceProfile',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingDeviceProfile.podspec'
  pod 'PingJourneyPlugin',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingJourneyPlugin.podspec'
  pod 'PingNetwork',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingNetwork.podspec'
  pod 'PingTamperDetector',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingTamperDetector.podspec'
  pod 'PingCommons',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/SDKS-4648-RN-Device/PingCommons.podspec'
  pod 'PingOidc',
  :podspec => 'https://raw.githubusercontent.com/ForgeRock/ping-ios-sdk/refs/tags/1.3.1/PingOidc.podspec'
  pod 'RNPingCore', :path => '../../packages/core'
  
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end

    # TODO: Remove workaround when PingTamperDetector is fixed or SPM is used
    # Fix missing FOUNDATION_EXPORT for TamperDetectorVersionString in PingTamperDetector
    tamper_header = File.join(
      installer.sandbox.root.to_s,
      'PingTamperDetector',
      'TamperDetector',
      'TamperDetector',
      'TamperDetector.h'
    )
    if File.exist?(tamper_header)
      contents = File.read(tamper_header)
      if contents.include?('TamperDetectorVersionString') &&
          !contents.include?('const unsigned char TamperDetectorVersionString')
        fixed = contents.sub(
          /TamperDetectorVersionString\s*\z/,
          'FOUNDATION_EXPORT const unsigned char TamperDetectorVersionString[];'
        )
        File.write(tamper_header, fixed)
      end
    end
  end
end
