# Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.

source 'https://rubygems.org'

ruby ">= 2.6.10"

gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '~> 1.27.0'
gem 'concurrent-ruby', '< 1.3.4'
gem 'ffi', '< 1.17'

gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
